In [1]:
import numpy as np
import pandas as pd
import csv

In [2]:
import Bio
from Bio import SeqIO
from Bio.Seq import Seq

In [7]:
HG = list(SeqIO.parse('HW2_reads.fasta', "fasta"))

In [8]:
HG

[SeqRecord(seq=Seq('CCCTGTCTACCACCCAGACTATCGTGTAGTTCTGCCTGTTCCGTAAGTCGTAGA...CGT'), id='1', name='1', description='1', dbxrefs=[]),
 SeqRecord(seq=Seq('AGACTATCGTGTAGTTCTGCCTGTTCCGTAAGTCGTAGATTGCTATCCTGGAAA...GTT'), id='2', name='2', description='2', dbxrefs=[]),
 SeqRecord(seq=Seq('TCTGCCTGTTCCGTAAGTCGTAGATTGCTATCCTGGAAATCATCGTGCTCAGGA...ATC'), id='3', name='3', description='3', dbxrefs=[]),
 SeqRecord(seq=Seq('AGTCGTAGATTGCTATCCTGGAAATCATCGTGCTCAGGATGTTAATATCTAGCG...AGG'), id='4', name='4', description='4', dbxrefs=[]),
 SeqRecord(seq=Seq('TCCTGGAAATCATCGTGCTCAGGATGTTAATATCTAGCGTCCTACGTTACGAGT...TGT'), id='5', name='5', description='5', dbxrefs=[]),
 SeqRecord(seq=Seq('TGCTCAGGATGTTAATATCTAGCGTCCTACGTTACGAGTTGGCAGATGACAGAT...GTG'), id='6', name='6', description='6', dbxrefs=[]),
 SeqRecord(seq=Seq('TATCTAGCGTCCTACGTTACGAGTTGGCAGATGACAGATCGTAGTCGTGGTAAG...CCA'), id='7', name='7', description='7', dbxrefs=[]),
 SeqRecord(seq=Seq('GTTACGAGTTGGCAGATGACAGATCGTAGTCGTGGTAAGGGGCATTGCCGCTTG...CAG'), id='8', name='8', description='8', dbxrefs=[]),
 SeqRecord(seq=Seq('ATGACAGATCGTAGTCGTGGTAAGGGGCATTGCCGCTTGTGACCCAGTTCGCGT...GGC'), id='9', name='9', description='9', dbxrefs=[]),
 SeqRecord(seq=Seq('CGTGGTAAGGGGCATTGCCGCTTGTGACCCAGTTCGCGTGCCTAGCAGCACTCC...TAG'), id='10', name='10', description='10', dbxrefs=[]),
 SeqRecord(seq=Seq('TGCCGCTTGTGACCCAGTTCGCGTGCCTAGCAGCACTCCAAAATAAAGTTTACA...CCT'), id='11', name='11', description='11', dbxrefs=[]),
 SeqRecord(seq=Seq('AGTTCGCGTGCCTAGCAGCACTCCAAAATAAAGTTTACAGTACCGTCCGGACGG...TTG'), id='12', name='12', description='12', dbxrefs=[]),
 SeqRecord(seq=Seq('CAGCACTCCAAAATAAAGTTTACAGTACCGTCCGGACGGCAGAACTGTCCTCTA...ACT'), id='13', name='13', description='13', dbxrefs=[]),
 SeqRecord(seq=Seq('AAGTTTACAGTACCGTCCGGACGGCAGAACTGTCCTCTAGATCGTCCTAACGCC...CGT'), id='14', name='14', description='14', dbxrefs=[]),
 SeqRecord(seq=Seq('TCCGGACGGCAGAACTGTCCTCTAGATCGTCCTAACGCCTTAGTCGAATCCCTT...AGA'), id='15', name='15', description='15', dbxrefs=[]),
 SeqRecord(seq=Seq('TGTCCTCTAGATCGTCCTAACGCCTTAGTCGAATCCCTTGCCGTCGGTAACCAC...GTA'), id='16', name='16', description='16', dbxrefs=[]),
 SeqRecord(seq=Seq('CCTAACGCCTTAGTCGAATCCCTTGCCGTCGGTAACCACTGAATAAACTACGCG...AGC'), id='17', name='17', description='17', dbxrefs=[]),
 SeqRecord(seq=Seq('GAATCCCTTGCCGTCGGTAACCACTGAATAAACTACGCGTTAGGACTTTGTCAG...ATT'), id='18', name='18', description='18', dbxrefs=[]),
 SeqRecord(seq=Seq('GGTAACCACTGAATAAACTACGCGTTAGGACTTTGTCAGACGCGAGGAGCTAGT...TAG'), id='19', name='19', description='19', dbxrefs=[]),
 SeqRecord(seq=Seq('AACTACGCGTTAGGACTTTGTCAGACGCGAGGAGCTAGTAGGAGGACAAATCAG...TTG'), id='20', name='20', description='20', dbxrefs=[]),
 SeqRecord(seq=Seq('CTTTGTCAGACGCGAGGAGCTAGTAGGAGGACAAATCAGCAAACGACCCTGAAT...TTC'), id='21', name='21', description='21', dbxrefs=[]),
 SeqRecord(seq=Seq('GGAGCTAGTAGGAGGACAAATCAGCAAACGACCCTGAATTGAACAATGTGAGTA...GCA'), id='22', name='22', description='22', dbxrefs=[]),
 SeqRecord(seq=Seq('ACAAATCAGCAAACGACCCTGAATTGAACAATGTGAGTAGGTATAACTGTGCTT...GCA'), id='23', name='23', description='23', dbxrefs=[]),
 SeqRecord(seq=Seq('ACCCTGAATTGAACAATGTGAGTAGGTATAACTGTGCTTGTATGACGTCCCGTT...AGC'), id='24', name='24', description='24', dbxrefs=[]),
 SeqRecord(seq=Seq('ATGTGAGTAGGTATAACTGTGCTTGTATGACGTCCCGTTCGGTCGTTCTTGAGC...GTT'), id='25', name='25', description='25', dbxrefs=[]),
 SeqRecord(seq=Seq('ACTGTGCTTGTATGACGTCCCGTTCGGTCGTTCTTGAGCAACTTCGGCCAGTGC...CGG'), id='26', name='26', description='26', dbxrefs=[]),
 SeqRecord(seq=Seq('CGTCCCGTTCGGTCGTTCTTGAGCAACTTCGGCCAGTGCATGCTATGGGGGAAG...TGC'), id='27', name='27', description='27', dbxrefs=[]),
 SeqRecord(seq=Seq('TTCTTGAGCAACTTCGGCCAGTGCATGCTATGGGGGAAGCTATGAATTCTATGT...GTT'), id='28', name='28', description='28', dbxrefs=[]),
 SeqRecord(seq=Seq('GGCCAGTGCATGCTATGGGGGAAGCTATGAATTCTATGTTGGAACTTGGGCCCG...TGG'), id='29', name='29', description='29', dbxrefs=[]),
 SeqRecord(seq=Seq('TGGGGGAAGCTATGAATTCTATGTTGGAACTTGGGCCCGGCATAGTAGTTTATG...TCA'), id='30', name='30', description='30', dbxrefs=[]),
 SeqRecord(seq=Seq('ATTCTATGTTGGAACTTGGGCCCGGCATAGTAGTTTATGCCTGTGGACCGGTGT...TAA'), id='31', name='31', description='31', dbxrefs=[]),
 SeqRecord(seq=Seq('TTGGGCCCGGCATAGTAGTTTATGCCTGTGGACCGGTGTTGAGTGTATCTGCTG...CTA'), id='32', name='32', description='32', dbxrefs=[]),
 SeqRecord(seq=Seq('TAGTTTATGCCTGTGGACCGGTGTTGAGTGTATCTGCTGGACCCCGGCGCGTTC...CGT'), id='33', name='33', description='33', dbxrefs=[]),
 SeqRecord(seq=Seq('GACCGGTGTTGAGTGTATCTGCTGGACCCCGGCGCGTTCACCTGTCCACATCTA...TCG'), id='34', name='34', description='34', dbxrefs=[]),
 SeqRecord(seq=Seq('TATCTGCTGGACCCCGGCGCGTTCACCTGTCCACATCTAATCCAAACATATACT...CAC'), id='35', name='35', description='35', dbxrefs=[]),
 SeqRecord(seq=Seq('GGCGCGTTCACCTGTCCACATCTAATCCAAACATATACTATTGGTATTTGAGCG...ACC'), id='36', name='36', description='36', dbxrefs=[]),
 SeqRecord(seq=Seq('CCACATCTAATCCAAACATATACTATTGGTATTTGAGCGTCTCACAACGACATC...TGA'), id='37', name='37', description='37', dbxrefs=[]),
 SeqRecord(seq=Seq('ACATATACTATTGGTATTTGAGCGTCTCACAACGACATCGACTGGTATTAGACA...GAC'), id='38', name='38', description='38', dbxrefs=[]),
 SeqRecord(seq=Seq('ATTTGAGCGTCTCACAACGACATCGACTGGTATTAGACACCTACCAGGAACAAC...TTG'), id='39', name='39', description='39', dbxrefs=[]),
 SeqRecord(seq=Seq('AACGACATCGACTGGTATTAGACACCTACCAGGAACAACCAATCGGTTTAGATG...GTG'), id='40', name='40', description='40', dbxrefs=[]),
 SeqRecord(seq=Seq('TATTAGACACCTACCAGGAACAACCAATCGGTTTAGATGACGCACAGCCACGGA...CTG'), id='41', name='41', description='41', dbxrefs=[]),
 SeqRecord(seq=Seq('AGGAACAACCAATCGGTTTAGATGACGCACAGCCACGGACAGCCTCTGTTGCTT...CTA'), id='42', name='42', description='42', dbxrefs=[]),
 SeqRecord(seq=Seq('GTTTAGATGACGCACAGCCACGGACAGCCTCTGTTGCTTGAGCAGTCCCAAAGT...TCG'), id='43', name='43', description='43', dbxrefs=[]),
 SeqRecord(seq=Seq('AGCCACGGACAGCCTCTGTTGCTTGAGCAGTCCCAAAGTGCGTACCTGAAGCCT...CTC'), id='44', name='44', description='44', dbxrefs=[]),
 SeqRecord(seq=Seq('CTGTTGCTTGAGCAGTCCCAAAGTGCGTACCTGAAGCCTGCCAAAACGTAGCCT...GTA'), id='45', name='45', description='45', dbxrefs=[]),
 SeqRecord(seq=Seq('TCCCAAAGTGCGTACCTGAAGCCTGCCAAAACGTAGCCTAGGCAAATGCCCGTC...CCA'), id='46', name='46', description='46', dbxrefs=[]),
 SeqRecord(seq=Seq('CTGAAGCCTGCCAAAACGTAGCCTAGGCAAATGCCCGTCGTCTTGCTCATAACT...AGA'), id='47', name='47', description='47', dbxrefs=[]),
 SeqRecord(seq=Seq('ACGTAGCCTAGGCAAATGCCCGTCGTCTTGCTCATAACTCCTTGGGACTGGCGT...AGA'), id='48', name='48', description='48', dbxrefs=[]),
 SeqRecord(seq=Seq('ATGCCCGTCGTCTTGCTCATAACTCCTTGGGACTGGCGTATCCATAAATAATCC...GGA'), id='49', name='49', description='49', dbxrefs=[]),
 SeqRecord(seq=Seq('CTCATAACTCCTTGGGACTGGCGTATCCATAAATAATCCATTCGATTCCTTGAG...CGC'), id='50', name='50', description='50', dbxrefs=[]),
 SeqRecord(seq=Seq('GACTGGCGTATCCATAAATAATCCATTCGATTCCTTGAGAGTTCCACATTAGAG...AGA'), id='51', name='51', description='51', dbxrefs=[]),
 SeqRecord(seq=Seq('AAATAATCCATTCGATTCCTTGAGAGTTCCACATTAGAGACTTATCCATCGAGG...CAT'), id='52', name='52', description='52', dbxrefs=[]),
 SeqRecord(seq=Seq('TTCCTTGAGAGTTCCACATTAGAGACTTATCCATCGAGGATCAGGCCAAATCCG...GGT'), id='53', name='53', description='53', dbxrefs=[]),
 SeqRecord(seq=Seq('ACATTAGAGACTTATCCATCGAGGATCAGGCCAAATCCGCGAGACCCGACCGAG...TTA'), id='54', name='54', description='54', dbxrefs=[]),
 SeqRecord(seq=Seq('CCATCGAGGATCAGGCCAAATCCGCGAGACCCGACCGAGATCAAGTATAACTCA...TGT'), id='55', name='55', description='55', dbxrefs=[]),
 SeqRecord(seq=Seq('CCAAATCCGCGAGACCCGACCGAGATCAAGTATAACTCATTACGCGTGGTGTGG...TGG'), id='56', name='56', description='56', dbxrefs=[]),
 SeqRecord(seq=Seq('CCGACCGAGATCAAGTATAACTCATTACGCGTGGTGTGGTTGCGGCCCACCCTT...CTC'), id='57', name='57', description='57', dbxrefs=[]),
 SeqRecord(seq=Seq('TATAACTCATTACGCGTGGTGTGGTTGCGGCCCACCCTTATCGTGAGCCAGTTG...CCC'), id='58', name='58', description='58', dbxrefs=[]),
 SeqRecord(seq=Seq('GTGGTGTGGTTGCGGCCCACCCTTATCGTGAGCCAGTTGTTGGATATACCCCTG...TGG'), id='59', name='59', description='59', dbxrefs=[]),
 SeqRecord(seq=Seq('CCCACCCTTATCGTGAGCCAGTTGTTGGATATACCCCTGGGCGGGCCTAAAGCT...AGC'), id='60', name='60', description='60', dbxrefs=[]),
 SeqRecord(seq=Seq('AGCCAGTTGTTGGATATACCCCTGGGCGGGCCTAAAGCTCCGCAACGAACACCC...GTA'), id='61', name='61', description='61', dbxrefs=[]),
 SeqRecord(seq=Seq('ATACCCCTGGGCGGGCCTAAAGCTCCGCAACGAACACCCCCTCCGCTGTGTCTG...ACG'), id='62', name='62', description='62', dbxrefs=[]),
 SeqRecord(seq=Seq('CCTAAAGCTCCGCAACGAACACCCCCTCCGCTGTGTCTGGTCGATTCTGGCTAG...TCT'), id='63', name='63', description='63', dbxrefs=[]),
 SeqRecord(seq=Seq('CGAACACCCCCTCCGCTGTGTCTGGTCGATTCTGGCTAGCCGCTCCGTTTGGGT...GTC'), id='64', name='64', description='64', dbxrefs=[]),
 SeqRecord(seq=Seq('CTGTGTCTGGTCGATTCTGGCTAGCCGCTCCGTTTGGGTAACAAATCACAGGAC...AGC'), id='65', name='65', description='65', dbxrefs=[]),
 SeqRecord(seq=Seq('TCTGGCTAGCCGCTCCGTTTGGGTAACAAATCACAGGACGCCATGGATTGCCTC...TCT'), id='66', name='66', description='66', dbxrefs=[]),
 SeqRecord(seq=Seq('CGTTTGGGTAACAAATCACAGGACGCCATGGATTGCCTCTTAAGTCTGGCCAGT...GCA'), id='67', name='67', description='67', dbxrefs=[]),
 SeqRecord(seq=Seq('TCACAGGACGCCATGGATTGCCTCTTAAGTCTGGCCAGTCGGGATGTCCTGCAG...ATT'), id='68', name='68', description='68', dbxrefs=[]),
 SeqRecord(seq=Seq('GATTGCCTCTTAAGTCTGGCCAGTCGGGATGTCCTGCAGCCCGGGTCACTTCTC...TTT'), id='69', name='69', description='69', dbxrefs=[]),
 SeqRecord(seq=Seq('CTGGCCAGTCGGGATGTCCTGCAGCCCGGGTCACTTCTCTGGTACCCTCTTGGC...ATA'), id='70', name='70', description='70', dbxrefs=[]),
 SeqRecord(seq=Seq('GTCCTGCAGCCCGGGTCACTTCTCTGGTACCCTCTTGGCATAACTTCTTCAAAT...GTA'), id='71', name='71', description='71', dbxrefs=[]),
 SeqRecord(seq=Seq('TCACTTCTCTGGTACCCTCTTGGCATAACTTCTTCAAATTTAGAGTTTAATGTT...CGC'), id='72', name='72', description='72', dbxrefs=[]),
 SeqRecord(seq=Seq('CCTCTTGGCATAACTTCTTCAAATTTAGAGTTTAATGTTTCGGGTGAGCTGCAT...TAC'), id='73', name='73', description='73', dbxrefs=[]),
 SeqRecord(seq=Seq('TCTTCAAATTTAGAGTTTAATGTTTCGGGTGAGCTGCATACTGTGATGGGGGGT...ATG'), id='74', name='74', description='74', dbxrefs=[]),
 SeqRecord(seq=Seq('TTTAATGTTTCGGGTGAGCTGCATACTGTGATGGGGGGTACTTGGCGTCAAGCG...TAC'), id='75', name='75', description='75', dbxrefs=[]),
 SeqRecord(seq=Seq('GAGCTGCATACTGTGATGGGGGGTACTTGGCGTCAAGCGCCACCTTTAGTAGTA...CCC'), id='76', name='76', description='76', dbxrefs=[]),
 SeqRecord(seq=Seq('ATGGGGGGTACTTGGCGTCAAGCGCCACCTTTAGTAGTACTCGAAAAGGCTCAT...ACC'), id='77', name='77', description='77', dbxrefs=[]),
 SeqRecord(seq=Seq('CGTCAAGCGCCACCTTTAGTAGTACTCGAAAAGGCTCATGGTAAACCGTGCATA...GTG'), id='78', name='78', description='78', dbxrefs=[]),
 SeqRecord(seq=Seq('TTAGTAGTACTCGAAAAGGCTCATGGTAAACCGTGCATACGTTCTAAGGTTCCC...TAC'), id='79', name='79', description='79', dbxrefs=[]),
 SeqRecord(seq=Seq('AAGGCTCATGGTAAACCGTGCATACGTTCTAAGGTTCCCCGCTATGGACTGGAC...GTG'), id='80', name='80', description='80', dbxrefs=[]),
 SeqRecord(seq=Seq('CCGTGCATACGTTCTAAGGTTCCCCGCTATGGACTGGACCGACCACGAAGTGGT...CCT'), id='81', name='81', description='81', dbxrefs=[]),
 SeqRecord(seq=Seq('AAGGTTCCCCGCTATGGACTGGACCGACCACGAAGTGGTGGATCATGAGACGTA...GCG'), id='82', name='82', description='82', dbxrefs=[]),
 SeqRecord(seq=Seq('GGACTGGACCGACCACGAAGTGGTGGATCATGAGACGTACCTGCTTAAGTCGGT...TAA'), id='83', name='83', description='83', dbxrefs=[]),
 SeqRecord(seq=Seq('CGAAGTGGTGGATCATGAGACGTACCTGCTTAAGTCGGTGATTGACGTCACACC...TAA'), id='84', name='84', description='84', dbxrefs=[]),
 SeqRecord(seq=Seq('TGAGACGTACCTGCTTAAGTCGGTGATTGACGTCACACCTCTCGCGCCCATAGC...GTT'), id='85', name='85', description='85', dbxrefs=[]),
 SeqRecord(seq=Seq('TAAGTCGGTGATTGACGTCACACCTCTCGCGCCCATAGCGAAGCTTATGTACTA...GGA'), id='86', name='86', description='86', dbxrefs=[]),
 SeqRecord(seq=Seq('CGTCACACCTCTCGCGCCCATAGCGAAGCTTATGTACTAAACCCCTTAGTGTTA...GCT'), id='87', name='87', description='87', dbxrefs=[]),
 SeqRecord(seq=Seq('GCCCATAGCGAAGCTTATGTACTAAACCCCTTAGTGTTAAGTCCTTACATCTGT...CTT'), id='88', name='88', description='88', dbxrefs=[]),
 SeqRecord(seq=Seq('TATGTACTAAACCCCTTAGTGTTAAGTCCTTACATCTGTTATGTCTATTGGAGG...ATA'), id='89', name='89', description='89', dbxrefs=[]),
 SeqRecord(seq=Seq('TTAGTGTTAAGTCCTTACATCTGTTATGTCTATTGGAGGACAAGGGGTGTACGC...TTC'), id='90', name='90', description='90', dbxrefs=[]),
 SeqRecord(seq=Seq('TACATCTGTTATGTCTATTGGAGGACAAGGGGTGTACGCTGCACAGAGCCTTCT...CCG'), id='91', name='91', description='91', dbxrefs=[]),
 SeqRecord(seq=Seq('TATTGGAGGACAAGGGGTGTACGCTGCACAGAGCCTTCTTCAGGTAGGAAGAAT...CTG'), id='92', name='92', description='92', dbxrefs=[]),
 SeqRecord(seq=Seq('GGTGTACGCTGCACAGAGCCTTCTTCAGGTAGGAAGAATACAAAATGCCTTTTT...AAT'), id='93', name='93', description='93', dbxrefs=[]),
 SeqRecord(seq=Seq('GAGCCTTCTTCAGGTAGGAAGAATACAAAATGCCTTTTTCGACACGTATAAGCC...AGA'), id='94', name='94', description='94', dbxrefs=[]),
 SeqRecord(seq=Seq('AGGAAGAATACAAAATGCCTTTTTCGACACGTATAAGCCGACGAGAGTAACACT...CTG'), id='95', name='95', description='95', dbxrefs=[]),
 SeqRecord(seq=Seq('TGCCTTTTTCGACACGTATAAGCCGACGAGAGTAACACTGATATCAGCGAAAAA...AGG'), id='96', name='96', description='96', dbxrefs=[]),
 SeqRecord(seq=Seq('GTATAAGCCGACGAGAGTAACACTGATATCAGCGAAAAATGGGCCCGGGTGTAG...TCG'), id='97', name='97', description='97', dbxrefs=[]),
 SeqRecord(seq=Seq('AGTAACACTGATATCAGCGAAAAATGGGCCCGGGTGTAGAGCGATGTATTTGCT...TTT'), id='98', name='98', description='98', dbxrefs=[]),
 SeqRecord(seq=Seq('AGCGAAAAATGGGCCCGGGTGTAGAGCGATGTATTTGCTGTTTTATGTGTCCAG...GAC'), id='99', name='99', description='99', dbxrefs=[]),
 SeqRecord(seq=Seq('CGGGTGTAGAGCGATGTATTTGCTGTTTTATGTGTCCAGGCAACTCCTAACGTC...CAA'), id='100', name='100', description='100', dbxrefs=[]),
 SeqRecord(seq=Seq('GTATTTGCTGTTTTATGTGTCCAGGCAACTCCTAACGTCGTTAAGAAGCACCTT...CTT'), id='101', name='101', description='101', dbxrefs=[]),
 SeqRecord(seq=Seq('TGTGTCCAGGCAACTCCTAACGTCGTTAAGAAGCACCTTTCTTAGATCCACCGA...ACT'), id='102', name='102', description='102', dbxrefs=[]),
 SeqRecord(seq=Seq('CCTAACGTCGTTAAGAAGCACCTTTCTTAGATCCACCGACCCGCGCTGCCTACA...AAA'), id='103', name='103', description='103', dbxrefs=[]),
 SeqRecord(seq=Seq('AAGCACCTTTCTTAGATCCACCGACCCGCGCTGCCTACAATGAGCACTTGTGCT...GAC'), id='104', name='104', description='104', dbxrefs=[]),
 SeqRecord(seq=Seq('ATCCACCGACCCGCGCTGCCTACAATGAGCACTTGTGCTTCTCATATTTAATAC...CGG'), id='105', name='105', description='105', dbxrefs=[]),
 SeqRecord(seq=Seq('CTGCCTACAATGAGCACTTGTGCTTCTCATATTTAATACTTCGCATACCTAGAA...AGT'), id='106', name='106', description='106', dbxrefs=[]),
 SeqRecord(seq=Seq('ACTTGTGCTTCTCATATTTAATACTTCGCATACCTAGAAACCACAAGTAGCTGA...CTT'), id='107', name='107', description='107', dbxrefs=[]),
 SeqRecord(seq=Seq('ATTTAATACTTCGCATACCTAGAAACCACAAGTAGCTGACCGACTAACGCAACG...TCC'), id='108', name='108', description='108', dbxrefs=[]),
 SeqRecord(seq=Seq('TACCTAGAAACCACAAGTAGCTGACCGACTAACGCAACGGCTTCGATGATAAAG...ATC'), id='109', name='109', description='109', dbxrefs=[]),
 SeqRecord(seq=Seq('AGTAGCTGACCGACTAACGCAACGGCTTCGATGATAAAGTATTGACCTTTCGCT...TTC'), id='110', name='110', description='110', dbxrefs=[]),
 SeqRecord(seq=Seq('AACGCAACGGCTTCGATGATAAAGTATTGACCTTTCGCTTTTTTGACATACTTC...TCT'), id='111', name='111', description='111', dbxrefs=[]),
 SeqRecord(seq=Seq('ATGATAAAGTATTGACCTTTCGCTTTTTTGACATACTTCCCCGTCACCTGCGAT...AAG'), id='112', name='112', description='112', dbxrefs=[]),
 SeqRecord(seq=Seq('CCTTTCGCTTTTTTGACATACTTCCCCGTCACCTGCGATCGGGCCCGGTGTGTT...TAA'), id='113', name='113', description='113', dbxrefs=[]),
 SeqRecord(seq=Seq('ACATACTTCCCCGTCACCTGCGATCGGGCCCGGTGTGTTCATATACGATGCCTC...AAT'), id='114', name='114', description='114', dbxrefs=[]),
 SeqRecord(seq=Seq('ACCTGCGATCGGGCCCGGTGTGTTCATATACGATGCCTCTCCACTTGTCGACAA...AAG'), id='115', name='115', description='115', dbxrefs=[]),
 SeqRecord(seq=Seq('CGGTGTGTTCATATACGATGCCTCTCCACTTGTCGACAAGCCAGTCACTATGTA...GCT'), id='116', name='116', description='116', dbxrefs=[]),
 SeqRecord(seq=Seq('CGATGCCTCTCCACTTGTCGACAAGCCAGTCACTATGTAAGCGAACCACCATAA...TGA'), id='117', name='117', description='117', dbxrefs=[]),
 SeqRecord(seq=Seq('TGTCGACAAGCCAGTCACTATGTAAGCGAACCACCATAATTGATCGACGATAAA...GAG'), id='118', name='118', description='118', dbxrefs=[]),
 SeqRecord(seq=Seq('CACTATGTAAGCGAACCACCATAATTGATCGACGATAAAGTGACGCGTCCATGC...ACC'), id='119', name='119', description='119', dbxrefs=[]),
 SeqRecord(seq=Seq('CCACCATAATTGATCGACGATAAAGTGACGCGTCCATGCTCATGTATTTATATG...CGA'), id='120', name='120', description='120', dbxrefs=[]),
 SeqRecord(seq=Seq('GACGATAAAGTGACGCGTCCATGCTCATGTATTTATATGACGGCCAAAAATGGA...TGC'), id='121', name='121', description='121', dbxrefs=[]),
 SeqRecord(seq=Seq('CGTCCATGCTCATGTATTTATATGACGGCCAAAAATGGAGATATTATAGTCGAC...TTC'), id='122', name='122', description='122', dbxrefs=[]),
 SeqRecord(seq=Seq('ATTTATATGACGGCCAAAAATGGAGATATTATAGTCGACCAAGTATTGGCGTCG...ACG'), id='123', name='123', description='123', dbxrefs=[]),
 SeqRecord(seq=Seq('AAAAATGGAGATATTATAGTCGACCAAGTATTGGCGTCGAACAACCGCGCCCTG...AAC'), id='124', name='124', description='124', dbxrefs=[]),
 SeqRecord(seq=Seq('ATAGTCGACCAAGTATTGGCGTCGAACAACCGCGCCCTGCAGAATCCCAAGATT...GCT'), id='125', name='125', description='125', dbxrefs=[]),
 SeqRecord(seq=Seq('TTGGCGTCGAACAACCGCGCCCTGCAGAATCCCAAGATTCGCCAGGCGGCGAAC...TTT'), id='126', name='126', description='126', dbxrefs=[]),
 SeqRecord(seq=Seq('CGCGCCCTGCAGAATCCCAAGATTCGCCAGGCGGCGAACGAGGCCTACGGGCAA...GAA'), id='127', name='127', description='127', dbxrefs=[])]

In [9]:
df = pd.DataFrame()
ID = []
Seq = []

for r in HG: 
    ID.append(r.name)
    Seq.append(r.seq)
    
df['ID'] = ID
df['Sequence'] = Seq

In [10]:
df

      ID                                           Sequence
0      1  (C, C, C, T, G, T, C, T, A, C, C, A, C, C, C, ...
1      2  (A, G, A, C, T, A, T, C, G, T, G, T, A, G, T, ...
2      3  (T, C, T, G, C, C, T, G, T, T, C, C, G, T, A, ...
3      4  (A, G, T, C, G, T, A, G, A, T, T, G, C, T, A, ...
4      5  (T, C, C, T, G, G, A, A, A, T, C, A, T, C, G, ...
..   ...                                                ...
122  123  (A, T, T, T, A, T, A, T, G, A, C, G, G, C, C, ...
123  124  (A, A, A, A, A, T, G, G, A, G, A, T, A, T, T, ...
124  125  (A, T, A, G, T, C, G, A, C, C, A, A, G, T, A, ...
125  126  (T, T, G, G, C, G, T, C, G, A, A, C, A, A, C, ...
126  127  (C, G, C, G, C, C, C, T, G, C, A, G, A, A, T, ...

[127 rows x 2 columns]

In [11]:
df.to_csv('fragmented_reads_table.csv')